name: Test inside QEMU 

on: 
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    # All branches

jobs: 
  build-os-image:
    runs-on: 
      labels: ubuntu-22.04-8core

    steps:
    - uses: actions/checkout@v4

    - name: Install needed packages
      run: |
        sudo apt update 
        sudo apt install binfmt-support qemu qemu-user-static sshpass 
        sudo update-binfmts --enable 

    - name: Build the Linux kernel for QEMU 
      run: ./setup-qemu-kernel.sh 

    - name: Build the full images 
      run: |
        ./dobuild.sh 

    - name: Decompress the SDK image 
      run: |
        IMAGE_BASE_PATH=$HOME/groundlight-pi-gen/deploy
        # Decompress with xz 
        xz -d $IMAGE_BASE_PATH/image_*-GroundlightPi-sdk-only-qemu.img.xz 

    - name: Start the Emulator 
      run: |
        IMAGE_BASE_PATH=$HOME/groundlight-pi-gen/deploy
        ./rpistart.sh -i $IMAGE_BASE_PATH/image_*-GroundlightPi-sdk-only-qemu.img
        # Copy the test script 
        sshpass -p "raspberry" scp -P 2222 tests/test_build_works.py pi@localhost:/home/pi
        # SSH into it 
        sshpass -p "raspberry" ssh -l pi localhost -p 2222
        python test_build_works.py 

